/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulina Euceda, David Bendeck, José Zúniga, Judá Ponce
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setResizable(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("FILE MANAGER");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Archivos = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Campos = new javax.swing.JDialog();
        boton_regresar = new javax.swing.JButton();
        boton_BorrarCampos = new javax.swing.JButton();
        boton_ModificarCampos = new javax.swing.JButton();
        boton_CrearCampo = new javax.swing.JButton();
        boton_ListarCampos1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        Registros = new javax.swing.JDialog();
        Indiices = new javax.swing.JDialog();
        Estandarización = new javax.swing.JDialog();
        crearCampos = new javax.swing.JDialog();
        NombreCampo = new javax.swing.JTextField();
        comboTipos = new javax.swing.JComboBox<>();
        CBytes = new javax.swing.JSpinner();
        RB_Si = new javax.swing.JRadioButton();
        RB_No = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Modificar_Campos = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        btn_aceptar1 = new javax.swing.JButton();
        btn_regresar1 = new javax.swing.JButton();
        cb_listaCampos = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        MDC_NombreCampo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        MDC_comboTipos = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        MDC_CBytes = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        MDC_RB_Si = new javax.swing.JRadioButton();
        MDC_RB_No = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        fondo_Modificar = new javax.swing.JLabel();
        Listar_Campos = new javax.swing.JDialog();
        btn_return = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_campos = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Borrar_campos = new javax.swing.JDialog();
        btn_regresar2 = new javax.swing.JButton();
        btn_delete1 = new javax.swing.JButton();
        fondo_delete = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Boton_Archivos = new javax.swing.JButton();
        boton_Indices = new javax.swing.JButton();
        Boton_Campos = new javax.swing.JButton();
        boton_Estandarizacion = new javax.swing.JButton();
        boton_Registros = new javax.swing.JButton();
        boton_Salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boton_Salir1 = new javax.swing.JButton();

        Archivos.setUndecorated(true);
        Archivos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda (1).png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        Archivos.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 170, 70));

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ARCHIVOS");
        Archivos.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 250, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archives2.gif"))); // NOI18N
        Archivos.getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 900, 660));

        Campos.setUndecorated(true);
        Campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_regresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        boton_regresar.setText("Regresar");
        boton_regresar.setContentAreaFilled(false);
        boton_regresar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda (1).png"))); // NOI18N
        boton_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_regresarMouseClicked(evt);
            }
        });
        boton_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresarActionPerformed(evt);
            }
        });
        Campos.getContentPane().add(boton_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, 90));

        boton_BorrarCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_BorrarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        boton_BorrarCampos.setText("Borrar Campos");
        boton_BorrarCampos.setContentAreaFilled(false);
        boton_BorrarCampos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_BorrarCampos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_BorrarCampos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar (1).png"))); // NOI18N
        boton_BorrarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_BorrarCamposMouseClicked(evt);
            }
        });
        Campos.getContentPane().add(boton_BorrarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 210, 80));

        boton_ModificarCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_ModificarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        boton_ModificarCampos.setText("Modificar Campos");
        boton_ModificarCampos.setContentAreaFilled(false);
        boton_ModificarCampos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_ModificarCampos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_ModificarCampos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz (1).png"))); // NOI18N
        boton_ModificarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ModificarCamposMouseClicked(evt);
            }
        });
        Campos.getContentPane().add(boton_ModificarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 210, 100));

        boton_CrearCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_CrearCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/base-de-datos.png"))); // NOI18N
        boton_CrearCampo.setText("Crear campos");
        boton_CrearCampo.setContentAreaFilled(false);
        boton_CrearCampo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_CrearCampo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_CrearCampo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/base-de-datos (1).png"))); // NOI18N
        boton_CrearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_CrearCampoMouseClicked(evt);
            }
        });
        Campos.getContentPane().add(boton_CrearCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, 100));

        boton_ListarCampos1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_ListarCampos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-de-la-compra.png"))); // NOI18N
        boton_ListarCampos1.setText("Listar Campos");
        boton_ListarCampos1.setContentAreaFilled(false);
        boton_ListarCampos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_ListarCampos1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_ListarCampos1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-de-la-compra (1).png"))); // NOI18N
        boton_ListarCampos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ListarCampos1MouseClicked(evt);
            }
        });
        Campos.getContentPane().add(boton_ListarCampos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 240, 80));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CAMPOS");
        Campos.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 150, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campos3.gif"))); // NOI18N
        Campos.getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 710, 410));

        crearCampos.setUndecorated(true);
        crearCampos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        crearCampos.getContentPane().add(NombreCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, 30));

        comboTipos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Char", "Boolean", "String", " " }));
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });
        crearCampos.getContentPane().add(comboTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, 20));

        CBytes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CBytes.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        crearCampos.getContentPane().add(CBytes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 60, -1));

        buttonGroup1.add(RB_Si);
        RB_Si.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RB_Si.setText("Si");
        crearCampos.getContentPane().add(RB_Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        buttonGroup1.add(RB_No);
        RB_No.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RB_No.setText("No");
        crearCampos.getContentPane().add(RB_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nombre del campo");
        crearCampos.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tipo de dato");
        crearCampos.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Numero de bytes");
        crearCampos.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Llave primaria");
        crearCampos.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 110, 30));

        btn_confirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agree.png"))); // NOI18N
        btn_confirmar.setText("Aceptar");
        btn_confirmar.setContentAreaFilled(false);
        btn_confirmar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_confirmar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_confirmar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agree (1).png"))); // NOI18N
        btn_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmarMouseClicked(evt);
            }
        });
        crearCampos.getContentPane().add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 180, 80));

        btn_regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/return (6).png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/return (7).png"))); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        crearCampos.getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 200, 80));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camp.jpg"))); // NOI18N
        crearCampos.getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 440));

        Modificar_Campos.setUndecorated(true);
        Modificar_Campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Por favor, seleccione el campo a modificar");
        Modificar_Campos.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 30));

        btn_aceptar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_aceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/create.png"))); // NOI18N
        btn_aceptar1.setText("Modifcar");
        btn_aceptar1.setContentAreaFilled(false);
        btn_aceptar1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_aceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_aceptar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/create (1).png"))); // NOI18N
        btn_aceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aceptar1MouseClicked(evt);
            }
        });
        Modificar_Campos.getContentPane().add(btn_aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 70));

        btn_regresar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_regresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        btn_regresar1.setText("Regresar");
        btn_regresar1.setContentAreaFilled(false);
        btn_regresar1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_regresar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_regresar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda (1).png"))); // NOI18N
        btn_regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresar1MouseClicked(evt);
            }
        });
        Modificar_Campos.getContentPane().add(btn_regresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 150, 70));

        cb_listaCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_listaCampos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listaCamposItemStateChanged(evt);
            }
        });
        Modificar_Campos.getContentPane().add(cb_listaCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nombre del campo");
        Modificar_Campos.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        MDC_NombreCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modificar_Campos.getContentPane().add(MDC_NombreCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 130, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Tipo de dato");
        Modificar_Campos.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        MDC_comboTipos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MDC_comboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Char", "Boolean", "String", " " }));
        MDC_comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDC_comboTiposActionPerformed(evt);
            }
        });
        Modificar_Campos.getContentPane().add(MDC_comboTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Numero de bytes");
        Modificar_Campos.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        MDC_CBytes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MDC_CBytes.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Modificar_Campos.getContentPane().add(MDC_CBytes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Llave primaria");
        Modificar_Campos.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 20));

        buttonGroup2.add(MDC_RB_Si);
        MDC_RB_Si.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MDC_RB_Si.setText("Si");
        Modificar_Campos.getContentPane().add(MDC_RB_Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        buttonGroup2.add(MDC_RB_No);
        MDC_RB_No.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MDC_RB_No.setText("No");
        Modificar_Campos.getContentPane().add(MDC_RB_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seleccionar3.jpg"))); // NOI18N
        Modificar_Campos.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 400));

        fondo_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seleccionar3.jpg"))); // NOI18N
        Modificar_Campos.getContentPane().add(fondo_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 620, 400));

        Listar_Campos.setUndecorated(true);
        Listar_Campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_return.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        btn_return.setText("Regresar");
        btn_return.setContentAreaFilled(false);
        btn_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_return.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_return.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda (1).png"))); // NOI18N
        btn_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_returnMouseClicked(evt);
            }
        });
        Listar_Campos.getContentPane().add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 150, 80));

        Lista_campos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Lista_campos);

        Listar_Campos.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 210, 250));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Lista de campos de este archivo");
        Listar_Campos.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 280, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listar.jpg"))); // NOI18N
        Listar_Campos.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        Borrar_campos.setUndecorated(true);
        Borrar_campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_regresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        btn_regresar2.setText("Regresar");
        btn_regresar2.setContentAreaFilled(false);
        btn_regresar2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_regresar2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_regresar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda (1).png"))); // NOI18N
        btn_regresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresar2MouseClicked(evt);
            }
        });
        Borrar_campos.getContentPane().add(btn_regresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 140, 60));

        btn_delete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        btn_delete1.setText("Borrar campo");
        btn_delete1.setContentAreaFilled(false);
        btn_delete1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_delete1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_delete1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (1).png"))); // NOI18N
        Borrar_campos.getContentPane().add(btn_delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 160, 80));

        fondo_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar1.png"))); // NOI18N
        Borrar_campos.getContentPane().add(fondo_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 820, 440));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Archivos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Boton_Archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder.png"))); // NOI18N
        Boton_Archivos.setText("Archivos");
        Boton_Archivos.setContentAreaFilled(false);
        Boton_Archivos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Boton_Archivos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Boton_Archivos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder (1).png"))); // NOI18N
        Boton_Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_ArchivosMouseClicked(evt);
            }
        });
        getContentPane().add(Boton_Archivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 170, 110));

        boton_Indices.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Indices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/index.png"))); // NOI18N
        boton_Indices.setText("Indices");
        boton_Indices.setContentAreaFilled(false);
        boton_Indices.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Indices.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Indices.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/index (1).png"))); // NOI18N
        boton_Indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_IndicesActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Indices, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 170, 70));

        Boton_Campos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Boton_Campos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard.png"))); // NOI18N
        Boton_Campos.setText("Campos");
        Boton_Campos.setContentAreaFilled(false);
        Boton_Campos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Boton_Campos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Boton_Campos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard (1).png"))); // NOI18N
        Boton_Campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_CamposMouseClicked(evt);
            }
        });
        Boton_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CamposActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 190, 90));

        boton_Estandarizacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Estandarizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        boton_Estandarizacion.setContentAreaFilled(false);
        boton_Estandarizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Estandarizacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check (1).png"))); // NOI18N
        boton_Estandarizacion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(boton_Estandarizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 200, 60));

        boton_Registros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/register (3)_1.png"))); // NOI18N
        boton_Registros.setText("Registros");
        boton_Registros.setContentAreaFilled(false);
        boton_Registros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Registros.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Registros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/register (4)_1.png"))); // NOI18N
        boton_Registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 190, 90));

        boton_Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit (4).png"))); // NOI18N
        boton_Salir.setContentAreaFilled(false);
        boton_Salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Salir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit (5).png"))); // NOI18N
        boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_SalirMouseClicked(evt);
            }
        });
        boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 90, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 20, 100));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Estandarización");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 370, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 1320, 820));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 150, 70, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 30, 1340, 840));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1140, -20, 1310, 900));

        boton_Salir1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit (4).png"))); // NOI18N
        boton_Salir1.setContentAreaFilled(false);
        boton_Salir1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Salir1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Salir1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit (5).png"))); // NOI18N
        boton_Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_Salir1MouseClicked(evt);
            }
        });
        boton_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 90, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_IndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_IndicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_IndicesActionPerformed

    private void boton_RegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_RegistrosActionPerformed

    private void Boton_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_CamposActionPerformed

    private void boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_SalirActionPerformed

    private void boton_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_boton_SalirMouseClicked

    private void Boton_ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_ArchivosMouseClicked
        Archivos.pack();
        Archivos.setModal(true);
        Archivos.setLocationRelativeTo(null);
        Archivos.setVisible(true);
    }//GEN-LAST:event_Boton_ArchivosMouseClicked

    private void Boton_CamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CamposMouseClicked
        Campos.pack();
        Campos.setModal(true);
        Campos.setLocationRelativeTo(null);
        Campos.setVisible(true);
    }//GEN-LAST:event_Boton_CamposMouseClicked

    private void boton_Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_Salir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Salir1MouseClicked

    private void boton_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Salir1ActionPerformed

    private void boton_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresarMouseClicked
        Campos.setVisible(false);
    }//GEN-LAST:event_boton_regresarMouseClicked

    private void boton_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_regresarActionPerformed

    private void boton_BorrarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_BorrarCamposMouseClicked
        Campos.setVisible(false);
        Borrar_campos.pack();
        Borrar_campos.setModal(true);
        Borrar_campos.setLocationRelativeTo(null);
        Borrar_campos.setVisible(true);
    }//GEN-LAST:event_boton_BorrarCamposMouseClicked

    private void boton_ModificarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ModificarCamposMouseClicked
        cb_listaCampos.setModel(new DefaultComboBoxModel<>());
        for (Campo campo : archivoFalso.getListaCampos()) {
            cb_listaCampos.addItem(campo);
        }
        Campos.setVisible(false);
        Modificar_Campos.pack();
        Modificar_Campos.setModal(true);
        Modificar_Campos.setLocationRelativeTo(null);
        Modificar_Campos.setVisible(true);
    }//GEN-LAST:event_boton_ModificarCamposMouseClicked

    private void boton_CrearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_CrearCampoMouseClicked
        Campos.setVisible(false);
        crearCampos.pack();
        crearCampos.setModal(true);
        crearCampos.setLocationRelativeTo(null);
        crearCampos.setVisible(true);

    }//GEN-LAST:event_boton_CrearCampoMouseClicked

    private void boton_ListarCampos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ListarCampos1MouseClicked
        Campos.setVisible(false);
        Listar_Campos.pack();
        Listar_Campos.setModal(true);
        Listar_Campos.setLocationRelativeTo(null);
        Listar_Campos.setVisible(true);
    }//GEN-LAST:event_boton_ListarCampos1MouseClicked

    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiposActionPerformed

    private void btn_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmarMouseClicked
        String nombre = NombreCampo.getText();
        String tipoDato = comboTipos.getSelectedItem().toString();
        int nBytes = CBytes.getValue().hashCode();
        boolean llave = RB_Si.isSelected();
        int reply = JOptionPane.showConfirmDialog(null, "Desea continuar añadiendo campos?", "Campo creado exitosamente!", JOptionPane.YES_NO_OPTION);
        // aqui hay que guardar en el archivo
        Campo nuevoCampo = new Campo(nombre, tipoDato, nBytes, llave);
        archivoFalso.setListaCampo(nuevoCampo);
        if (reply == JOptionPane.NO_OPTION) {
            crearCampos.setVisible(false);
            Campos.setVisible(true);

        }
        NombreCampo.setText("");
        comboTipos.setSelectedIndex(0);
        CBytes.setValue(0);
//        (llave) ? RB_Si.doClick() : RB_No.doClick();
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btn_confirmarMouseClicked

    private void MDC_comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDC_comboTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDC_comboTiposActionPerformed

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        crearCampos.setVisible(false);
        Campos.setVisible(true);
    }//GEN-LAST:event_btn_regresarMouseClicked

    private void btn_regresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresar1MouseClicked
        Modificar_Campos.setVisible(false);
        Campos.setVisible(true);
    }//GEN-LAST:event_btn_regresar1MouseClicked

    private void cb_listaCamposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listaCamposItemStateChanged
        Campo campoAct = (Campo) cb_listaCampos.getSelectedItem();
        if (cb_listaCampos.getSelectedItem() != null) {
            buttonGroup2.clearSelection();
            MDC_NombreCampo.setText(campoAct.getNombre());
            MDC_comboTipos.setSelectedItem(campoAct.getTipo());
            MDC_CBytes.setValue(campoAct.getBytes());
            if (campoAct.isLprimaria()) {
                MDC_RB_Si.doClick();
            } else {
                MDC_RB_No.doClick();
            }
        }
        //algun tipo de validacion para ver si no hay mas llaves primarias supogo
    }//GEN-LAST:event_cb_listaCamposItemStateChanged

    private void btn_aceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aceptar1MouseClicked
        Campo.class.cast(cb_listaCampos.getSelectedItem()).setNombre(MDC_NombreCampo.getText());
        //algun tipo de validacion para ver si no hay mas llaves primarias supogo
        Campo.class.cast(cb_listaCampos.getSelectedItem()).setLprimaria(MDC_RB_Si.isSelected());
        Campo.class.cast(cb_listaCampos.getSelectedItem()).setBytes(MDC_CBytes.getValue().hashCode());
        Campo.class.cast(cb_listaCampos.getSelectedItem()).setTipo(MDC_comboTipos.getSelectedItem().toString());
    }//GEN-LAST:event_btn_aceptar1MouseClicked

    private void btn_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnMouseClicked
        Listar_Campos.setVisible(false);
        Campos.setVisible(true);
    }//GEN-LAST:event_btn_returnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       Archivos.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresar2MouseClicked
        Borrar_campos.setVisible(false);
        Campos.setVisible(true);
    }//GEN-LAST:event_btn_regresar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Archivos;
    private javax.swing.JDialog Borrar_campos;
    private javax.swing.JButton Boton_Archivos;
    private javax.swing.JButton Boton_Campos;
    private javax.swing.JSpinner CBytes;
    private javax.swing.JDialog Campos;
    private javax.swing.JDialog Estandarización;
    private javax.swing.JLabel Fondo;
    private javax.swing.JDialog Indiices;
    private javax.swing.JList<String> Lista_campos;
    private javax.swing.JDialog Listar_Campos;
    private javax.swing.JSpinner MDC_CBytes;
    private javax.swing.JTextField MDC_NombreCampo;
    private javax.swing.JRadioButton MDC_RB_No;
    private javax.swing.JRadioButton MDC_RB_Si;
    private javax.swing.JComboBox<String> MDC_comboTipos;
    private javax.swing.JDialog Modificar_Campos;
    private javax.swing.JTextField NombreCampo;
    private javax.swing.JRadioButton RB_No;
    private javax.swing.JRadioButton RB_Si;
    private javax.swing.JDialog Registros;
    private javax.swing.JButton boton_BorrarCampos;
    private javax.swing.JButton boton_CrearCampo;
    private javax.swing.JButton boton_Estandarizacion;
    private javax.swing.JButton boton_Indices;
    private javax.swing.JButton boton_ListarCampos1;
    private javax.swing.JButton boton_ModificarCampos;
    private javax.swing.JButton boton_Registros;
    private javax.swing.JButton boton_Salir;
    private javax.swing.JButton boton_Salir1;
    private javax.swing.JButton boton_regresar;
    private javax.swing.JButton btn_aceptar1;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_regresar1;
    private javax.swing.JButton btn_regresar2;
    private javax.swing.JButton btn_return;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<Object> cb_listaCampos;
    private javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JDialog crearCampos;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo_Modificar;
    private javax.swing.JLabel fondo_delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Archivo archivoFalso = new Archivo();//solo es prueba
}
