/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author Paulina Euceda, David Bendeck, José Zúniga, Judá Ponce
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setResizable(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("FILE MANAGER");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Archivos = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Campos = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        Registros = new javax.swing.JDialog();
        Indiices = new javax.swing.JDialog();
        Estandarización = new javax.swing.JDialog();
        Boton_Archivos = new javax.swing.JButton();
        boton_Indices = new javax.swing.JButton();
        Boton_Campos = new javax.swing.JButton();
        boton_Estandarizacion = new javax.swing.JButton();
        boton_Registros = new javax.swing.JButton();
        boton_Registros1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        Archivos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ARCHIVOS");
        Archivos.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 250, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archives.jpg"))); // NOI18N
        Archivos.getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 860));

        Campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Campos.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 350));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Archivos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Boton_Archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder.png"))); // NOI18N
        Boton_Archivos.setText("Archivos");
        Boton_Archivos.setContentAreaFilled(false);
        Boton_Archivos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Boton_Archivos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Boton_Archivos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder (1).png"))); // NOI18N
        Boton_Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_ArchivosMouseClicked(evt);
            }
        });
        getContentPane().add(Boton_Archivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 170, 110));

        boton_Indices.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Indices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/index.png"))); // NOI18N
        boton_Indices.setText("Indices");
        boton_Indices.setContentAreaFilled(false);
        boton_Indices.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Indices.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Indices.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/index (1).png"))); // NOI18N
        boton_Indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_IndicesActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Indices, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 170, 70));

        Boton_Campos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Boton_Campos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard.png"))); // NOI18N
        Boton_Campos.setText("Campos");
        Boton_Campos.setContentAreaFilled(false);
        Boton_Campos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Boton_Campos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Boton_Campos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard (1).png"))); // NOI18N
        Boton_Campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_CamposMouseClicked(evt);
            }
        });
        Boton_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CamposActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 190, 90));

        boton_Estandarizacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Estandarizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        boton_Estandarizacion.setContentAreaFilled(false);
        boton_Estandarizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Estandarizacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check (1).png"))); // NOI18N
        boton_Estandarizacion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(boton_Estandarizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 200, 60));

        boton_Registros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/register (3)_1.png"))); // NOI18N
        boton_Registros.setText("Registros");
        boton_Registros.setContentAreaFilled(false);
        boton_Registros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Registros.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Registros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/register (4)_1.png"))); // NOI18N
        boton_Registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 190, 90));

        boton_Registros1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_Registros1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit (4).png"))); // NOI18N
        boton_Registros1.setContentAreaFilled(false);
        boton_Registros1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boton_Registros1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Registros1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit (5).png"))); // NOI18N
        boton_Registros1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_Registros1MouseClicked(evt);
            }
        });
        boton_Registros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Registros1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Registros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 90, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 20, 100));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Estandarización");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 370, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 1320, 820));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 150, 70, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 30, 1340, 840));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConLogo.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1140, -20, 1310, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_IndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_IndicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_IndicesActionPerformed

    private void boton_RegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_RegistrosActionPerformed

    private void Boton_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_CamposActionPerformed

    private void boton_Registros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Registros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Registros1ActionPerformed

    private void boton_Registros1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_Registros1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_boton_Registros1MouseClicked

    private void Boton_ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_ArchivosMouseClicked
        Archivos.pack();
        Archivos.setModal(true);
        Archivos.setLocationRelativeTo(null);
        Archivos.setVisible(true);
    }//GEN-LAST:event_Boton_ArchivosMouseClicked

    private void Boton_CamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CamposMouseClicked
        Campos.pack();
        Campos.setModal(true);
        Campos.setLocationRelativeTo(null);
        Campos.setVisible(true);
    }//GEN-LAST:event_Boton_CamposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Archivos;
    private javax.swing.JButton Boton_Archivos;
    private javax.swing.JButton Boton_Campos;
    private javax.swing.JDialog Campos;
    private javax.swing.JDialog Estandarización;
    private javax.swing.JLabel Fondo;
    private javax.swing.JDialog Indiices;
    private javax.swing.JDialog Registros;
    private javax.swing.JButton boton_Estandarizacion;
    private javax.swing.JButton boton_Indices;
    private javax.swing.JButton boton_Registros;
    private javax.swing.JButton boton_Registros1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
